name: adsdk
description: AdSdk is a wrapper around famous ad packages which let you integrate ads easily.
version: 1.1.0
homepage: https://github.com/Appyhigh/ad-sdk-flutter.git
repository: https://github.com/Appyhigh/ad-sdk-flutter.git

publish_to: "none"

environment:
  sdk: ^3.6.0


dependencies:
  applovin_max: ^4.2.1
  dart_jsonwebtoken: ^2.14.2
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.2.0
  http: ^1.2.2
  plugin_platform_interface: ^2.1.8
  shared_preferences: ^2.3.5
  shimmer: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.appyhigh.plugins.adsdk
        pluginClass: AdsdkPlugin
      ios:
        pluginClass: AdsdkPlugin

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf