name: adsdk
description: AdSdk is a wrapper around famous ad packages which let you integrate ads easily.
version: 0.0.1
homepage: https://github.com/Appyhigh/ad-sdk-flutter.git
repository: https://github.com/Appyhigh/ad-sdk-flutter.git

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  applovin_max: ^2.5.0
  dart_jsonwebtoken: ^2.7.1
  flutter:
    sdk: flutter
  google_mobile_ads: ^3.0.0
  http: ^0.13.6
  logger: ^1.3.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.appyhigh.plugins.adsdk
        pluginClass: AdsdkPlugin
      ios:
        pluginClass: AdsdkPlugin

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf